
<h4>Still ditt spørsmål om bussrutene i Trondheim her (fullstendig
norsk setning):</h4>

<form method="post" action="./tuc.inc">
<input type=hidden name="lang" value="sms" size=3>
<input type=text name="quest" value="" size=79> 
<input type=submit value=" Send spørsmål ">
<input type=reset value=" Nullstill ">
<nobr> <i>Vis teknisk informasjon i svaret</i>
<input type=checkbox name="tekniskinfo"></nobr>
</form>

<?PHP include('tuc.inc'); ?>
