##################################################
# file: PxSms_server.py
#
# skeleton generated by "ZSI.generate.wsdl2dispatch.ServiceModuleWriter"
#      /usr/bin/wsdl2py test.payex.com-pxsms.wsdl
#
##################################################

from ZSI.schema import GED, GTD
from ZSI.TCcompound import ComplexType, Struct
from PxSms_types import *
from ZSI.ServiceContainer import ServiceSOAPBinding

# Messages  
SendCpaSoapIn = GED("http://external.payex.com/PxSms/", "SendCpa").pyclass

SendCpaSoapOut = GED("http://external.payex.com/PxSms/", "SendCpaResponse").pyclass

SendLaSoapIn = GED("http://external.payex.com/PxSms/", "SendLa").pyclass

SendLaSoapOut = GED("http://external.payex.com/PxSms/", "SendLaResponse").pyclass

CheckSoapIn = GED("http://external.payex.com/PxSms/", "Check").pyclass

CheckSoapOut = GED("http://external.payex.com/PxSms/", "CheckResponse").pyclass


# Service Skeletons
class PxSms(ServiceSOAPBinding):
    soapAction = {}
    root = {}

    def __init__(self, post='/pxsms/pxsms.asmx', **kw):
        ServiceSOAPBinding.__init__(self, post)

    def soap_SendCpa(self, ps, **kw):
        request = ps.Parse(SendCpaSoapIn.typecode)
        return request,SendCpaSoapOut()

    soapAction['http://external.payex.com/PxSms/SendCpa'] = 'soap_SendCpa'
    root[(SendCpaSoapIn.typecode.nspname,SendCpaSoapIn.typecode.pname)] = 'soap_SendCpa'

    def soap_SendLa(self, ps, **kw):
        request = ps.Parse(SendLaSoapIn.typecode)
        return request,SendLaSoapOut()

    soapAction['http://external.payex.com/PxSms/SendLa'] = 'soap_SendLa'
    root[(SendLaSoapIn.typecode.nspname,SendLaSoapIn.typecode.pname)] = 'soap_SendLa'

    def soap_Check(self, ps, **kw):
        request = ps.Parse(CheckSoapIn.typecode)
        return request,CheckSoapOut()

    soapAction['http://external.payex.com/PxSms/Check'] = 'soap_Check'
    root[(CheckSoapIn.typecode.nspname,CheckSoapIn.typecode.pname)] = 'soap_Check'

