##################################################
# file: PxSms_client.py
# 
# client stubs generated by "ZSI.generate.wsdl2python.WriteServiceModule"
#     /usr/bin/wsdl2py test.payex.com-pxsms.wsdl
# 
##################################################

from PxSms_types import *
import urlparse, types
from ZSI.TCcompound import ComplexType, Struct
from ZSI import client
from ZSI.schema import GED, GTD
import ZSI

# Locator
class PxSmsLocator:
    PxSmsSoap_address = "https://test.payex.com/pxsms/pxsms.asmx"
    def getPxSmsSoapAddress(self):
        return PxSmsLocator.PxSmsSoap_address
    def getPxSmsSoap(self, url=None, **kw):
        return PxSmsSoapSOAP(url or PxSmsLocator.PxSmsSoap_address, **kw)

# Methods
class PxSmsSoapSOAP:
    def __init__(self, url, **kw):
        kw.setdefault("readerclass", None)
        kw.setdefault("writerclass", None)
        # no resource properties
        self.binding = client.Binding(url=url, **kw)
        # no ws-addressing

    # op: SendCpa
    def SendCpa(self, request, **kw):
        if isinstance(request, SendCpaSoapIn) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://external.payex.com/PxSms/SendCpa", **kw)
        # no output wsaction
        response = self.binding.Receive(SendCpaSoapOut.typecode)
        return response

    # op: SendLa
    def SendLa(self, request, **kw):
        if isinstance(request, SendLaSoapIn) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://external.payex.com/PxSms/SendLa", **kw)
        # no output wsaction
        response = self.binding.Receive(SendLaSoapOut.typecode)
        return response

    # op: Check
    def Check(self, request, **kw):
        if isinstance(request, CheckSoapIn) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://external.payex.com/PxSms/Check", **kw)
        # no output wsaction
        response = self.binding.Receive(CheckSoapOut.typecode)
        return response

SendCpaSoapIn = GED("http://external.payex.com/PxSms/", "SendCpa").pyclass

SendCpaSoapOut = GED("http://external.payex.com/PxSms/", "SendCpaResponse").pyclass

SendLaSoapIn = GED("http://external.payex.com/PxSms/", "SendLa").pyclass

SendLaSoapOut = GED("http://external.payex.com/PxSms/", "SendLaResponse").pyclass

CheckSoapIn = GED("http://external.payex.com/PxSms/", "Check").pyclass

CheckSoapOut = GED("http://external.payex.com/PxSms/", "CheckResponse").pyclass
