#! /usr/bin/python
# -*- coding: latin-1 -*-
# $Id$
""" 
Program to easily control starting and stopping of TTPD.

The actions include 'start', 'stop', 'restart', and 'store_alerts'
(the two latter ones are used in conjunction with log rotation).

Copyright (C) 2004 by Lingit AS
"""

__version__ = "$Rev$"
__author__ = "Martin Thorsen Ranang"

import optparse
import os
import re
import signal
import sys

import TTP.Options
import TTP.LogHandler

init_re = re.compile('^%s ttpd INFO TTPD, .+, r?e?-?initialized.$' % \
                     TTP.LogHandler.log_line_re_date)

pid_re = re.compile('^%s ttpd INFO PID = (?P<pid>\d+), ' % \
                    TTP.LogHandler.log_line_re_date)

def get_pid(log_file):

    pids = []
    
    f = open(log_file, 'r')

    pid_next = False
    
    for line in f:
        if pid_next:
            m = pid_re.match(line)
            if m:
                pids.append(m.group('pid'))
                pid_next = False
        else:
            if init_re.search(line):
                pid_next = True
                
    f.close()
    
    return pids[-1]


def main():
    """Module mainline (for standalone execution).
    """
    parser = optparse.OptionParser(usage = '%prog [options] ' \
                                   'start|stop|restart|store_alerts',
                                   version = '%%prog version %s' %
                                   (__version__))

    option_list = TTP.Options.common_options + TTP.Options.ttpd_options
    
    for option, description in option_list + TTP.Options.ttpdctl_options:
        TTP.Options.update_help(description)
        parser.add_option(*option, **description)
        
    # Parse the command line, to get the CONFIG_FILE value.
    options, args = parser.parse_args()
    
    # Update the default values of PARSER, so that the values in the
    # CONFIG_FILE takes presendence over the programmed defaults, and
    # the command-line supplied options gets the highest precedence.
    TTP.Options.parse_configuration(options.config_file, parser)
    
    # Reparse the command line to get the rest of the values.
    options, args = parser.parse_args()

    commands = ['start', 'stop', 'restart', 'store_alerts']
    
    actions = [x for x in args if x in commands]
    
    if len(actions) != 1:
        print 'You must supply one argument for what action to take.'
        sys.exit(1)
    else:
        action = actions[0]
    
    # Expand the any paths and make them absolute.
    options.log_file = os.path.abspath(os.path.expanduser(options.log_file))
    
    if not options.old_log_file:
        options.old_log_file = options.log_file
    else:
        options.old_log_file = \
                             os.path.abspath(os.path.expanduser(options.old_log_file))
    
    verbs = {'start': ('start', 'Process started'),
             'restart': ('restart', 'Process restarted', signal.SIGHUP),
             'store_alerts': ('store alerts', 'Alerts stored', signal.SIGUSR1),
             'stop': ('stop', 'Process stopped', signal.SIGINT)}
    
    if action in ['stop', 'restart', 'store_alerts']:

        if not os.access(options.log_file, os.F_OK | os.R_OK):
            print "You do not have access to read '%s'." % (options.log_file)
            
        pid = int(get_pid(options.old_log_file))
        
        print 'Will attempt to %s ttpd with pid = %d...' % (verbs[action][0],
                                                            pid)
        try:
            os.kill(pid, verbs[action][2])
        except OSError, reason:
            print 'Sorry, but the attempt ended with the error, "%s".' % reason
        print verbs[action][1]
        
    if action == 'start':
        
        # Find out which executable we should run.
        exec_file = None
        
        path, executable = os.path.split(options.executable)

        paths = [path]

        if paths == ['']:
            if os.environ['PATH']:
                paths += os.environ['PATH'].split(':')

        for path in paths:
            test_path = os.path.join(path, executable)
            if os.access(test_path, os.F_OK | os.X_OK):
                exec_file = test_path
                break
                
        if not exec_file:
            print "Could not find any executable '%s' in your PATH." % \
                  options.executable
            sys.exit(1)
        
        flags = ['%s=%s' % (x[0][1], getattr(options, x[1]['dest']))
                 for x in option_list if hasattr(options, x[1]['dest']) and \
                 x[1]['default'] != getattr(options, x[1]['dest'])]
        
        print 'Will attempt to %s %s with flags %s' % (verbs[action][0],
                                                       exec_file,
                                                       ' '.join(flags))
        try:
            os.system('%s %s' % (exec_file, ' '.join(flags)))
        except OSError, reason:
            print 'Sorry, but the attempt ended with the error, "%s".' % reason
        print verbs[action][1]
        
    return


if __name__ == "__main__":
    main()
